const data = [
  "Martabak Cokelat",
  "Naga Sakti",
  "Ratu Pantai Selatan",
  "Harimau Putih",
  "Raja Jin",
  "Dewi Bulan",
  "Penjaga Hutan",
  "Singa Emas",
  "Banteng Sakti",
  "Elang Perkasa",
  "Laba-laba Sunda",
  "Buaya Hitam",
  "Monyet Hutan",
  "Gajah Ngawi",
  "Kue Keju",
  "Rehan Toyota",
  "Ikbal Hotwil",
  "Kuda Pake Sendal",
  "Sendal ",
  "Jaket Bapak",
  "Kambing Hitam",
  "Pintu Gerbang",
  "Kayu Jati ",
  "Ayam Tidak Punya KTP",
  "Dino Sok Inggris",
  "Teh Sari Wangi",
  "Indomi Kecap Asin",
  "Burung Elang Dari Jawa",
  "Tidak Ada/Kosong !",
  "Nokia Bapak",
  "Telur Gulung",
  "Sayur Asem Kecap Manis",
  "Baju Terbang",
  "Sendal Jepit",
  "Nasi Padang",
  "Pizza Mewah",
  "Jus Alpukat",
  "Sate Ayam",
  "Gado-Gado",
  "Kambing Guling",
  "Tahu Bulat",
  "Lontong Balap",
  "Soto Ayam",
  "Bakso Gepeng",
  "Cilok Kenyal",
  "Mie Ayam Lezat",
  "Es Cendol Manis",
  "Kopi Hitam Mantap",
  "Brownies Lumer",
  "Kerak Telor",
  "Tempe Mendoan",
  "Jajanan Pasar",
  "Pecel Lele",
  "Ayam Geprek",
  "Roti Bakar",
  "Pisang Goreng",
  "Bubur Ayam",
  "Nasi Goreng Spesial",
  "Sop Buntut",
  "Gule Kambing",
  "Rawon Hitam",
  "Ikan Bakar",
  "Sate Kambing",
  "Kue Cubit",
  "Cakwe",
  "Tahu Gejrot",
  "Kacang Polong",
  "Sayur Bayam",
  "Sambal Terasi",
  "Es Dawet",
  "Teh Tarik",
  "Es Teler",
  "Kerupuk Kulit",
  "Rengginang",
  "Emping Melinjo",
  "Mie Goreng",
  "Risoles",
  "Lumpia Semarang",
  "Pempek Palembang",
  "Asinan Betawi",
  "Lemper Ayam",
  "Bika Ambon",
  "Klepon",
  "Kue Lumpur",
  "Putu Ayu",
  "Onde-Onde",
  "Pukis",
  "Serabi",
  "Martabak Telur",
  "Sempol Ayam",
  "Bubur Ketan Hitam",
  "Kai Cenat",
  "Ibu Kai Cenat",
  "Bapak Kai Cenat",
  "Es Dawet Ketan Hitam Pekat Oli Bekas",
  "Mio Mirza",
  "Kak Gem",
  "Uni Bakwan",
  "Sambal Goreng Kecap Hitam",
  "Kamu Bukan User Khodam !",
  "Kosong",
  "Gajah",
];

module.exports = data;
